const Types = {
  FETCH_CHARACTERS_START: 'characters/FETCH_CHARACTERS_START',
  FETCH_CHARACTERS_SUCCESS: 'characters/FETCH_CHARACTERS_SUCCESS',
  FETCH_CHARACTERS_ERROR: 'characters/FETCH_CHARACTERS_ERROR',
  FETCH_HOMEWORLD_SUCCESS: 'characters/FETCH_HOMEWORLD_SUCCESS',
  FETCH_HOMEWORLD_ERROR: 'characters/FETCH_HOMEWORLD_ERROR',
  FETCH_FILM_SUCCESS: 'characters/FETCH_FILM_SUCCESS',
  FETCH_FILM_ERROR: 'characters/FETCH_FILM_ERROR',
  FETCH_VEHICLE_SUCCESS: 'characters/FETCH_VEHICLE_SUCCESS',
  FETCH_VEHICLE_ERROR: 'characters/FETCH_VEHICLE_ERROR',
  FILTER_CHARACTERS: 'characters/FILTER_CHARACTERS',
  LIKE_CHARACTER: 'characters/LIKE_CHARACTER',
  REFRESH_CHARACTERS: 'characters/REFRESH_CHARACTERS',
  CLEAR_CHARACTERS: 'characters/CLEAR_CHARACTERS',
  ADD_CHARACTER_IMAGE: 'characters/ADD_CHARACTER_IMAGE',
  DELETE_CHARACTER_IMAGE: 'characters/DELETE_CHARACTER_IMAGE',
};

export default Types;
